name: codespell

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: codespell
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
