name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm install
    - run: npm run test:unit
    - uses: codecov/codecov-action@v2
      with:
        flags: unittests

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm install
    - run: npm run test:e2e
    - uses: codecov/codecov-action@v2
      with:
        flags: e2etests
